/*IMPORTAÇÃO DO PACOTE EXPRESS: */
const express = require('express');

/*CRIAÇÃO DE UMA INSTANCIA EXECUTAVEL DO EXPRESS */
const app = express();

/*
CRIAÇÃO DO SERVIDPR DE REQUISISÕES HTTP DA APLICAÇÃO PARAMETROS DO LISTEN
1 - PORTA LÓGICA QUE RECEBE AS REQUISIÇÕES
2 - CALLBACK - ARROW ANONIMA (OPCIONAL)
*/

app.listen(3000, ()=>{
    console.log('SERVIDOR RODANDO EM: http://localhost:3000');
});